### ISSUE TITLE
Error: path for html_dependency not provided

### ISSUE THREAD

**Issue by mwhitaker** [timelyportfolio/vueR#1]
Thanks for a great package. Having fun trying some of your [examples](https://github.com/timelyportfolio/vueR/blob/master/inst/examples/vue_component_examples.R) but when I try to render as a Rmd file to html I get this error. Eg:

```
mint <- htmlDependency(
  name = "mint-ui",
  version = "2.0.5",
  src = c(href="https://unpkg.com/mint-ui/lib"),
  script = "index.js",
  stylesheet = "style.css"
)
rmarkdown:::validate_html_dependency(mint)
#Error: path for html_dependency not provided
```
This has likely nothing to do with this package and is about rmarkdown/knitr, but if you could point me in the right direction to get the dependencies working for Rmd I'd appreciate it!

Michael

**Comment by timelyportfolio** [comment]
Thanks @mwhitaker.  I am really glad you are trying out `vueR`.  Please let me know if you have any `Vuejs` experience.  I am still not sure if I have determined the best patterns for R + `Vuejs`.

The error you are getting is super annoying and related to https://github.com/rstudio/rmarkdown/issues/794.  Unfortunately, there has been no response from the RStudio team on this.  The `href` works everywhere (console, Shiny, etc.) except `rmarkdown`.  To get around the issue, you will need to locally copy the `js` and `css` and reference that with `src=c(file="...")`.  Or, I might soon add some of these components to this package.  Unfortunately, the all-in `js` for many of these adds up quickly and would prevent CRAN submission.

Let me know if this doesn't make sense, and I will write up a quick demo.

**Comment by mwhitaker** [comment]
Thanks Kent, I was able to get this to work in my rmd file by adding the `js` and `css` dependencies manually, just like you suggested.  Still kicking the tires as var as `Vuejs` is concerned and if it makes sense in my workflow.

I think we may be kindred spirits as I love combining different systems/approaches/APIs, except I don't quite have the chops you do! Your contribution to [formattable/sparkline ](https://github.com/renkun-ken/formattable/issues/83#issuecomment-252485916) also very helpful.

**Comment by BilboBaagins** [comment]
Hi timelyportfolio, 
If you could do up a quick demo of this it would be much appreciated. 
Thanks

**Comment by d8aninja** [comment]
FWIW putting runtime: shiny in your yaml header cleared this same error when setting up a basic flexdashboard.

**Comment by timelyportfolio** [comment]
closing for now, but please reopen if anyone woud like to continue the discussion

**Comment by MichaelSodeke** [comment]
> 
> 
> Thanks Kent, I was able to get this to work in my rmd file by adding the `js` and `css` dependencies manually, just like you suggested. Still kicking the tires as var as `Vuejs` is concerned and if it makes sense in my workflow.
> 
> I think we may be kindred spirits as I love combining different systems/approaches/APIs, except I don't quite have the chops you do! Your contribution to [formattable/sparkline ](https://github.com/renkun-ken/formattable/issues/83#issuecomment-252485916) also very helpful.

@mwhitaker I am having the same issue. Can you show me how you managed to include the `js` and `css` dependencies manually?

**Comment by Leran10** [comment]
Hi, I'm trying to render a Rmarkdown file in linux and eventually I want it to generate a dynamic .html file for people to checkout. The command I'm using is 
`R -e "rmarkdown::render('./test_rshiny2.Rmd',output_file='./results/Diagnos_Plot.html')"`. 
However I kept getting this error: 
`Error: path for html_dependency not provided`. 

Can anyone here provide some help?
Thanks so much!!
