### ISSUE TITLE
Change installation instructions and other URLs to new Github Org

### ISSUE THREAD

**Issue by nezlicodes** [timelyportfolio/vueR#9]
I am getting the error:
` package ‘vueR’ is not available (for R version 4.0.0)`

whenever I try to install the package. 

Is there a way around this?

**Comment by JohnCoene** [comment]
It should work fine from Github.

```r
# install.packages('remotes')
remotes::install_github("vue-r/vueR")
```

Does it still give you that error?

**Comment by nezlicodes** [comment]
> 
> 
> It should work fine from Github.
> 
> ```r
> # install.packages('remotes')
> remotes::install_github("vue-r/vueR")
> ```
> 
> Does it still give you that error?

Yes.
But I ended up solving the issue by following the installation on this link:

https://rdrr.io/github/timelyportfolio/vueR/

**Comment by JohnCoene** [comment]
Yes @timelyportfolio moved this project to this organisation just a few days ago.

**Comment by nezlicodes** [comment]
> 
> 
> Yes @timelyportfolio moved this project to this organisation just a few days ago.

Thank you so much for you help.

**Comment by timelyportfolio** [comment]
@nezlicodes @JohnCoene I'll work to clean this up over the next couple of minutes.  @nezlicodes we'd love any ideas for improvements, suggestions, use cases, and we are planning for very active development over the next couple of weeks/months.

**Comment by timelyportfolio** [comment]
hopefully now resolved and I also switched travis to run on new org repo.

**Comment by nezlicodes** [comment]
Really thrilled to read that !
Also, if you ever launch a blog where you do a full app setup connecting VueJs and shiny, I'd be happy to read.

\o/

**Comment by timelyportfolio** [comment]
@nezlicodes We are currently working on a real world app and expect to demonstrate soon.  Some of the roadmap is contained in new issues over the last week.  Also I wanted to point you to https://github.com/vue-r/vueR/tree/master/inst/examples for some other mostly non-Shiny use cases.  Most work but some I will update over the next couple of days.

I will push updates to newest stable vue in a couple of minutes.  If you weren't aware `vue-next`/`vue3` is in Beta and I hope to add these dependencies so we can start to test with and use new Vue.

I'll close this issue for now, but please reopen if my "fixes" did not work.
